version: '2'
services:
  node:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/src/app/
    networks:
      - back-network

  database:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - back-network

networks:
  back-network:
    driver: bridge